In [3]:
# Creating a numeric vector
numeric_vector <- c(1, 2, 3, 4, 5) # 'c()' combines values into a vector
print(numeric_vector)

# Creating a character vector
character_vector <- c("apple", "banana", "cherry")
print(character_vector)

# Accessing elements of a vector
print(numeric_vector[3]) # Outputs the third element, which is 3


[1] 1 2 3 4 5
[1] "apple"  "banana" "cherry"
[1] 3


In [9]:
# Using c() to create a vector with specific values
vec_numeric <- c(1, 2, 3, 4, 5)
vec_character <- c("apple", "banana", "cherry")
vec_logical <- c(TRUE, FALSE, TRUE)

# Using the colon operator to create a sequence of numbers
vec_sequence <- 1:10 # Equivalent to c(1, 2, 3, ..., 10)

# Using the seq() function for more control over sequences
vec_seq_step <- seq(1, 10, by = 2) # Generates: 1, 3, 5, 7, 9

# Using rep() to repeat elements
vec_repeated <- rep(5, times = 3) # Repeats the number 5 three times: 5, 5, 5
vec_repeat_seq <- rep(1:3, each = 2) # Repeats each number twice: 1, 1, 2, 2, 3, 3


In [10]:
# Accessing the first element
first_element <- vec_numeric[1]

# Accessing multiple elements by specifying indices
subset_elements <- vec_numeric[c(2, 4)] # Elements at positions 2 and 4

# Excluding elements by using negative indices
exclude_first <- vec_numeric[-1] # All elements except the first

# Logical indexing
logical_indexed <- vec_numeric[vec_numeric > 2] # Only elements greater than 2


In [11]:
# Arithmetic operations
sum_vector <- vec_numeric + 10       # Adds 10 to each element
mult_vector <- vec_numeric * 2       # Multiplies each element by 2

# Summing all elements
total_sum <- sum(vec_numeric)

# Finding the mean and median
average <- mean(vec_numeric)
median_value <- median(vec_numeric)


In [12]:
# Minimum and maximum values
min_value <- min(vec_numeric)
max_value <- max(vec_numeric)

# Standard deviation and variance
std_dev <- sd(vec_numeric)
variance <- var(vec_numeric)


In [13]:
# Element-wise comparison (returns a logical vector)
is_greater_than_two <- vec_numeric > 2

# Checking for any or all true values
any_greater_than_two <- any(vec_numeric > 2)   # TRUE if any element is greater than 2
all_greater_than_two <- all(vec_numeric > 2)   # TRUE if all elements are greater than 2


In [14]:
# Sorting a vector
sorted_vector <- sort(vec_numeric)   # Sorts in ascending order by default

# Sorting in descending order
sorted_desc <- sort(vec_numeric, decreasing = TRUE)

# Ordering returns the indices that would sort the vector
order_indices <- order(vec_numeric)  # Useful for indexing original vector in sorted order


In [15]:
# Unique values in a vector
unique_values <- unique(c(1, 2, 2, 3, 4, 4, 5))

# Checking for duplicates
duplicates <- duplicated(c(1, 2, 2, 3, 4, 4, 5)) # TRUE for elements that have appeared before


In [16]:
# Combining two vectors
combined_vector <- c(vec_numeric, c(6, 7, 8)) # Joins vectors into a single vector

# Joining with paste() (for character vectors)
vec_text <- c("Hello", "world")
joined_text <- paste(vec_text, collapse = " ") # Joins elements with a space in between


In [17]:
vec_with_na <- c(1, 2, NA, 4, 5)

# Summing while ignoring NA values
sum_ignoring_na <- sum(vec_with_na, na.rm = TRUE)

# Identifying which elements are NA
na_positions <- is.na(vec_with_na)   # Returns TRUE for each NA element

# Removing NA values
vec_no_na <- vec_with_na[!is.na(vec_with_na)]


In [18]:
vec_short <- c(1, 2)
vec_long <- c(10, 20, 30, 40)

# Adding a shorter vector to a longer vector (1,2 is recycled)
recycled_result <- vec_long + vec_short # Results in: c(11, 22, 31, 42)


In [19]:
# Create a numeric vector
vec <- c(1, 3, 5, NA, 7, 9)

# Access elements, handle NA, and perform operations
print(vec[2])                      # Access second element
no_na <- vec[!is.na(vec)]          # Remove NA values
print(mean(no_na))                 # Compute mean without NA

# Create a sequence vector, add 10 to each element, and sort it
seq_vec <- 1:5
new_vec <- seq_vec + 10            # Adds 10 to each element
sorted_vec <- sort(new_vec)         # Sorts in ascending order
print(sorted_vec)

# Logical indexing: Only keep elements > 10
filtered_vec <- new_vec[new_vec > 10]
print(filtered_vec)


[1] 3
[1] 5
[1] 11 12 13 14 15
[1] 11 12 13 14 15


In [4]:
# Creating a list with different types of elements
my_list <- list(name="John", age=25, scores=c(85, 90, 88))
print(my_list)

# Accessing elements in a list
print(my_list$name)  # Accessing by name (outputs "John")
print(my_list[[2]])  # Accessing by index (outputs 25)


$name
[1] "John"

$age
[1] 25

$scores
[1] 85 90 88

[1] "John"
[1] 25


In [5]:
# Creating a 2x3 matrix
my_matrix <- matrix(1:6, nrow=2, ncol=3)
print(my_matrix)

# Accessing elements in a matrix
print(my_matrix[1, 2]) # Outputs the element in row 1, column 2 (which is 3)

# Adding row and column names
rownames(my_matrix) <- c("Row1", "Row2")
colnames(my_matrix) <- c("Col1", "Col2", "Col3")
print(my_matrix)


     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
[1] 3
     Col1 Col2 Col3
Row1    1    3    5
Row2    2    4    6


In [6]:
# Creating a 3-dimensional array
my_array <- array(1:12, dim = c(2, 3, 2))
print(my_array)

# Accessing elements in an array
print(my_array[1, 2, 1]) # Accessing the element in position (1,2,1), which is 3


, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

[1] 3


In [7]:
# Creating a data frame
my_data <- data.frame(
  Name = c("Alice", "Bob", "Charlie"),
  Age = c(24, 27, 22),
  Score = c(85.5, 90.0, 78.5)
)
print(my_data)

# Accessing elements in a data frame
print(my_data$Name)  # Accessing a column by name
print(my_data[1,])   # Accessing the first row


     Name Age Score
1   Alice  24  85.5
2     Bob  27  90.0
3 Charlie  22  78.5
[1] "Alice"   "Bob"     "Charlie"
   Name Age Score
1 Alice  24  85.5


In [8]:
# Creating a factor
gender <- factor(c("Male", "Female", "Female", "Male"))
print(gender)

# Checking the levels of a factor
print(levels(gender))

# Modifying factor levels
levels(gender) <- c("Female", "Male")
print(gender)


[1] Male   Female Female Male  
Levels: Female Male
[1] "Female" "Male"  
[1] Male   Female Female Male  
Levels: Female Male
