#### PyPi Package : NumPy

In [1]:
# pip install numpy
import numpy as np

In [4]:
# Given lists
list1 = [1, 2, 3]
list2 = [1, 2, 3]
print(list1+list2)

[1, 2, 3, 1, 2, 3]


In [6]:


# Initialize an empty list to store the results
result = []

# Loop through the lists using the index
for i in range(len(list1)):
    # Add corresponding elements and append to the result list
    sum_value = list1[i] + list2[i]
    result.append(sum_value)

# Print the result
print(result)

print(np.array(list1)+np.array(list2))


[2, 4, 6]
[2 4 6]


# Linear Algebra

In [7]:
a = np.ones((2, 3))
b = np.full((3, 2), 2)
print(a)
print("")
print("")
print(b)
print("")
print("")
print(np.matmul(a, b))

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

print("")
print(np.matmul(a, b))


[[1. 1. 1.]
 [1. 1. 1.]]


[[2 2]
 [2 2]
 [2 2]]


[[6. 6.]
 [6. 6.]]

[[19 22]
 [43 50]]


# Statistics

In [27]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
print(np.min(stats))
print(np.max(stats, axis=1))
print(np.max(stats))
print(np.sum(stats))
print(np.sum(stats, axis=0))
print("Mean",np.mean(stats))
print((1+2+3+4+5+6)/6)

stats1 = np.array([[5, 4, 3], [2, 1, 6]])
print("median",np.median(stats1))
stats2 = np.array([[5, 4, 3], [2, 1, 6]])
print("Median for each row",np.median(stats2, axis=1))
stats3 = np.array([2,3,4,5,6,1,7])
print("Median from odd number",np.median(stats3))
stats4 = np.array([2,3,4,5,6,1,7,8])
print("Median from even number",np.median(stats4))

1
[3 6]
6
21
[5 7 9]
Mean 3.5
3.5
median 3.5
Median for each row [4. 2.]
Median from odd number 4.0
Median from even number 4.5


# Reorganizing Arrays

In [9]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)
print(before.size)
after = before.reshape((4, 2))
print(after)
print("")
after = before.reshape((1, 8))
print(after)
# print("")
after = before.reshape((2, 4))
print(after)
# print("")

[[1 2 3 4]
 [5 6 7 8]]
8
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 3 4 5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


## Vertically stacking vectors

In [35]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
print(np.vstack([v1, v2]))

[[1 2 3 4]
 [5 6 7 8]]


## Horizontal stacking

In [38]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

print(h1)
print(h2)
print(np.hstack((h1, h2)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


# Miscellaneous

## Load Data from File

In [10]:
filedata = np.genfromtxt('read_data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


## Boolean Masking and Advanced Indexing

In [13]:
mask = ((filedata > 10) & (filedata < 100))
print(mask)
print("")
mask = ((filedata > 10) | (filedata < 100))
print(mask)
print("")
mask = ~((filedata > 10) | (filedata < 100))
print(mask)

[[False  True  True  True False  True False False  True False False False
  False False False False False False]
 [False  True  True  True False  True False  True False False False False
  False False False False  True  True]
 [False  True  True  True False  True False False  True False False False
  False False False False  True  True]]

[[ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True]]

[[False False False False False False False False False False False False
  False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False]
 [False False False False False False False False False False False False
  False False Fals

# Additional Numpy Functions

## Flatten an array

In [16]:
print(before)
print(before.flatten())

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


## Reshape with unknown dimension (-1)

In [20]:
print(before)
reshaped = before.reshape(2, -1)
print(reshaped)
reshaped = before.reshape(4, -1)
print(reshaped)
reshaped = before.reshape(8, -1)
print(reshaped)


[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


## Transpose an array

In [21]:
print(before)
print(before.T)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


## Concatenate arrays

In [11]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])
print(np.concatenate((array1, array2), axis=0))


[[1 2]
 [3 4]
 [5 6]]


## Split arrays

In [12]:
array = np.array([1, 2, 3, 4, 5, 6])
arrays = np.split(array,2)
print(arrays)

[array([1, 2, 3]), array([4, 5, 6])]


## Find unique elements and counts

In [29]:
array = np.array([1, 2, 3, 1, 2,1,2,0,2, 4, 5])
unique_elements, counts = np.unique(array, return_counts=True)
print(unique_elements)
print(counts)

[0 1 2 3 4 5]
[1 3 4 1 1 1]


## Reshape for broadcasting

In [30]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print(a)
print(b)
print(a * b)

[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


## Applying a function element-wise

In [36]:
a = np.array([1, 2, 3])
print(np.sqrt(a))

[1.         1.41421356 1.73205081]


## Find indices of non-zero elements

In [37]:
a = np.array([0, 1, 2, 0, 3, 0])
print(np.nonzero(a))

(array([1, 2, 4], dtype=int64),)


## Sorting

In [38]:
a = np.array([[3, 2], [5, 1]])
print(np.sort(a, axis=None))

[1 2 3 5]


## Set operations

In [44]:
set1 = np.array([1, 2, 3, 4, 5])
set2 = np.array([3, 4, 5, 6, 7,8])
print(np.intersect1d(set1, set2))
print(np.union1d(set1, set2))
print(np.setdiff1d(set1, set2))
print(np.setdiff1d(set2, set1))
# print(np.setdiff1d(np.union1d(set1, set2),np.intersect1d(set1, set2)))
result = np.array(list(set(set1).symmetric_difference(set(set2))))
print(result)

[3 4 5]
[1 2 3 4 5 6 7 8]
[1 2]
[6 7 8]
[1 2 6 7 8]
[1 2 6 7 8]


## Generate a meshgrid

In [45]:
x = np.array([1, 2, 3])
y = np.array([4, 5])
X, Y = np.meshgrid(x, y)
print(X)
print(Y)

[[1 2 3]
 [1 2 3]]
[[4 4 4]
 [5 5 5]]


## Diagonal of an array

In [46]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(np.diagonal(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


## Flip an array

In [47]:
print(a)
print(np.flip(a, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


## Roll elements within an array

In [13]:
print(a)
print(np.roll(a, shift=1, axis=1))

[[1 2]
 [3 4]]
[[2 1]
 [4 3]]
