#### PyPi Package : NumPy

In [3]:
# pip install numpy
import numpy as np

In [2]:
list1=[10,10]
list2=[20,20]
result=list1+list2
print(result)


[10, 10, 20, 20]


In [9]:
list1=np.array(list1)
list2=np.array(list2)
print(list1+list2)


[30 30]


In [13]:
list1=np.array(list1)
list2=np.array(list2)
print(list1+list2)
print(type(list1))
print(type(list1))
print(list2.dtype)
list1=list1.astype("int16")
print(list1.dtype)

[30 30]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
int32
int16


# Array Initialization

In [17]:

# Array Initialization
# In this exercise, you will learn how to initialize an array in Python.
a = np.array([1, 2, 3], dtype='int32')
print(a)

[1 2 3]


In [18]:
# initialize an array as float type
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [20]:
# initialize an array as 3 dimension
c = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(c)



[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Get Dimension

In [21]:
# Get Dimension
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


## Get Shape

In [23]:
# Get Shape
print(a)
print('rows and columns',a.shape)
print(b)
print('rows and columns',b.shape)
print(c)
print('rows and columns',c.shape)

[1 2 3]
rows and columns (3,)
[[9. 8. 7.]
 [6. 5. 4.]]
rows and columns (2, 3)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
rows and columns (2, 2, 2)


## Get Type

In [24]:
# Get Type
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
int32


## Get Size (bytes per element)

In [25]:
# Get Size (bytes per element)
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

4
8
4


## Get total size (bytes for the whole array)

In [9]:
# Get total size (bytes for the whole array)
print(a.nbytes)
print(b.nbytes)
print(c.nbytes)

12
48
32


## Get number of elements

In [10]:
# Get number of elements
print(a.size)
print(b.size)
print(c.size)

3
6
8


# Accessing/Changing specific elements, rows, columns, etc

In [58]:
a = np.array([[1, 2, 3, 4, 5, 6, 7,8,9], [10, 20, 30, 40, 50, 60, 70,80,90]])
b = np.array([[1, 2, 3, 4, 5, 6, 7,8,9], [10, 20, 30, 40, 50, 60, 70,80,90],[11,21,31,41,51,61,71,81,91]])


## Get a specific element

In [30]:
# Get a specific element
print(a)
print(a[0, 2])
print(a[0, 5])
print(a[1, 5])

[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]]
3
6
60


## Get a specific row

In [39]:
# Get a specific row
print(a)
print("")
print(a[0, :])
print(a[0, :3])
print(a[0, 0:-1])
print(a[0, 0:-2])
print(a[0, :-3])
print(a[0, 2:4])

[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]]

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6]
[3 4]


## Get a specific column

In [46]:
# Get a specific column
print(a)
print("")

print("second column using index",a[:, 1])
print(a[1:, 3])
print("**************")
print(b)
print("")
print("first column from all rows using index",b[:,0])

[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]]

second column using index [ 2 20]
[40]
**************
[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]
 [11 21 31 41 51 61 71 81 91]]

first column from all rows using index [ 1 10 11]


## Get a specific range of elements

In [52]:
# Get a specific range of elements
print(a)
print("*********")
print(a[0, 1:-1:2])
print("************")
print(b)
print("************")
print(b[2, 1:-1:3])
print(b[0:3, 1:-1:3])

[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]]
*********
[2 4 6 8]
************
[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]
 [11 21 31 41 51 61 71 81 91]]
************
[21 51 81]
[[ 2  5  8]
 [20 50 80]
 [21 51 81]]


## Modify an element and replace a column

In [67]:
# Modify an element and replace a column
a = np.array([[1, 2, 3, 4, 5, 6, 7,8,9], [10, 20, 30, 40, 50, 60, 70,80,90]])
b = np.array([[1, 2, 3, 4, 5, 6, 7,8,9], [10, 20, 30, 40, 50, 60, 70,80,90],[11,21,31,41,51,61,71,81,91]])

print(a)
print("*************")
a[1, 5] = 222
print(a)
print("****************")
a[:, 2] = [0]
print(a)
print("****************")
a[:, 2] = [0,2]
print(a)

[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]]
*************
[[  1   2   3   4   5   6   7   8   9]
 [ 10  20  30  40  50 222  70  80  90]]
****************
[[  1   2   0   4   5   6   7   8   9]
 [ 10  20   0  40  50 222  70  80  90]]
****************
[[  1   2   0   4   5   6   7   8   9]
 [ 10  20   2  40  50 222  70  80  90]]


# Initializing Different Types of Arrays

In [69]:
# All 0s matrix
print(np.zeros((2, 3)))
print(np.zeros((2, 3)).ndim)

[[0. 0. 0.]
 [0. 0. 0.]]
2


In [19]:
# All 1s matrix
print((np.ones((4, 2, 2), dtype='int32')))
print((np.ones((4, 2, 2), dtype='int32')).ndim)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
3


In [70]:
print((np.ones((4, 3, 3), dtype='int32')))
print((np.ones((4, 3, 3), dtype='int32')).ndim)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
3


In [20]:
# Any other number
print(np.full((2, 2), 99))

[[99 99]
 [99 99]]


In [71]:
# Any other number (full_like)
print(np.full_like(a, 4))

[[4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4]]


In [80]:
# Random decimal numbers
print(np.random.rand(3, 3))

[[0.23511973 0.46503149 0.32407169]
 [0.89275786 0.06089155 0.15764026]
 [0.83627561 0.26906465 0.67854716]]


In [87]:
# Random Integer values
print(np.random.randint(1, 20, size=(3, 3)))

[[ 4  2 10]
 [16  1 12]
 [12 18  2]]


In [93]:
# The identity matrix
print(np.identity(7))

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [95]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


# Mathematics

In [96]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


## Basic Operations

In [97]:
print(a)
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


## Element-wise Operations

In [100]:
b = np.array([1, 0, 1, 0])
print(a)
print(b)
print("*********")
print(a + b)
print("********")
print(a ** 2)
print(np.cos(a))

[1 2 3 4]
[1 0 1 0]
*********
[2 2 4 4]
********
[ 1  4  9 16]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
